// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Volvo.Cadastro.Data;

namespace Volvo.Cadastro.Migrations
{
    [DbContext(typeof(CadastroContext))]
    partial class CadastroContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Volvo.Cadastro.Models.Caminhao", b =>
                {
                    b.Property<int>("IdCaminhao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idCaminhao")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnoFabricacao")
                        .HasColumnType("int")
                        .HasColumnName("anoFabricacao");

                    b.Property<int>("AnoModelo")
                        .HasColumnType("int")
                        .HasColumnName("anoModelo");

                    b.Property<int>("ModeloIdModelo")
                        .HasColumnType("int");

                    b.HasKey("IdCaminhao")
                        .HasName("idCaminhao");

                    b.HasIndex("ModeloIdModelo");

                    b.ToTable("tbCaminhao");
                });

            modelBuilder.Entity("Volvo.Cadastro.Models.Modelo", b =>
                {
                    b.Property<int>("IdModelo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idModelo")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescricaoModelo")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("descricao");

                    b.HasKey("IdModelo")
                        .HasName("idModelo");

                    b.ToTable("tbModelo");

                    b.HasData(
                        new
                        {
                            IdModelo = 1,
                            DescricaoModelo = "FH"
                        },
                        new
                        {
                            IdModelo = 2,
                            DescricaoModelo = "FM"
                        });
                });

            modelBuilder.Entity("Volvo.Cadastro.Models.Caminhao", b =>
                {
                    b.HasOne("Volvo.Cadastro.Models.Modelo", "Modelo")
                        .WithMany()
                        .HasForeignKey("ModeloIdModelo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modelo");
                });
#pragma warning restore 612, 618
        }
    }
}
